### PR TITLE
Update Norway region and localadmin records

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1757

This PR updates region and localadmin records in Norway to reflect new 2020 boundary changes. Commit notes below.

Once approved, I'll QA, validate, and merge.

### CODE REVIEW

**Comment by stepps00** [comment]
ee1c342: This commit adds new records at the region placetype, each representing a new "fylker"  created on 2020-01-01.

e206d23: Completes all the superseding, `edtf:` property work, and `mz:is_current` property work at the region placetype. Supersedes the existing (pre-2020 regions) into new region records, setting appropriate flags.

8fef34c: Updates geometries for unchanged divisions at region placetype, storing reversegeo properties and alt geometries.

**Comment by stepps00** [comment]
New region geometries, reflecting 2020 boundaries:

Screen Shot 2020-01-28 at 11 22 02 AM

**Comment by stepps00** [comment]
New localadmin geometries, reflecting 2020 boundaries:

Screen Shot 2020-01-30 at 5 05 52 PM

**Comment by stepps00** [comment]
Ready for PIP work.

**Comment by stepps00** [comment]
The image of regions above makes it appear that Oslo and another region are the same feature, but they are (correctly) different regions.

- data/856/870/89/85687089.geojson (Oslo)
- data/152/794/726/3/1527947263.geojson (Innlandet)

**Comment by stepps00** [comment]
PIP work on this branch revealed a few issues:

- Four localadmin records seem to have duplicate geometries
- Because the new geometries are clipped to land, some descendant localities on the coastline are losing parent_ids and ids in their hierarchies

I need to dig around a bit, hoping to merge this today after I PIP again.

**Comment by stepps00** [comment]
The two most recent commits fix duplicate issues at the localadmin placetype I noticed during PIP work. I'm going to PIP the branch again, validate, and merge to master.

**Comment by stepps00** [comment]
I reindexed my PIP service, but still seeing some hierarchy issues in descendant locality records. I need to debug more to find out where the issue lies - this is still in progress...

**Comment by missinglink** [comment]
distribution files were automagically generated 🎉 

- https://wof.synergy.io/sqlite/whosonfirst-data-admin-no-latest.db.bz2.json
- https://wof.synergy.io/bundles/whosonfirst-data-admin-no-latest.tar.bz2.json

**Pull request merged**
