### PR TITLE
Norway admin updates

### PR DESCRIPTION
**Pull request by stepps00**
WIP. WIll fix https://github.com/whosonfirst-data/whosonfirst-data/issues/298.

To do:
- [x] Update region placetype
- [x] Update localadmin placetype
- [x] Update locality placetype
- [x] Update neighbourhood placetype
- [x] Ensure alt_label is on all alt files
- [x] Ensure all lbl:bbox values are reset
- [x] Fixes issues around Asker/Sanvika
- [x] QA Oppegard area
- [x] Run wiki names script on records
- [x] Validate
- [x] PIP

### CODE REVIEW

**Comment by stepps00** [comment]
Commit Notes:

6af352d: Updated region records, superseding two regions that were dissolved in 2018 into a new region record.

c1a1615: This commit updated localities that maintained their name and geometry, but needed to be clipped to their parent localadmin geometry

072604d: Deprecated four existing records that had accurate geometries, but incorrect names. Created new records to supersede them into

9dc6b19: Deprecated existing records that needed to be split into various locality records. Created new records to supersede them into.

39060e8 and 03296bf: In some cases, a new record was created for a locality when WOF had an existing point record. These commits update the existing record with a new geom, untangle superseding, update props, and remove the "new" record that shouldn't have been created.

**Comment by stepps00** [comment]
Over to @nvkelso for review.

This PR cleans up Norway locality and neighbourhood records, with a slight tweak at the region level, too. Once approved, I'll update names, validate, PIP, and merge.

**Comment by nvkelso** [comment]
Commits look good. Let's look one more time heads up in QGIS and then I'll approve.

**Comment by nvkelso** [comment]
I had a few minor quibbles that can be addressed in this PR in a new commit, but fundamentally it looks good. Thanks!

**Comment by stepps00** [comment]
I also need to ensure that all new alt files have the `alt_label` property set before import so there are no issues with distributions.

**Comment by stepps00** [comment]
Commit notes are listed above, all properties and geometries in this branch validate.

I'm going to kick off the PIP work and circle back for one last review once hierarchies are updated.

**Comment by stepps00** [comment]
The most recent commit includes PIP work for this branch, though two region records seemingly lost their `wof:parent_id` value - we've simplified the Norway country geometry previously, now two region records' rev geo centroids fall outside the Norway country geometry.

I'll update these two records with new rev geo centroids, re-PIP, then QA once more before merging.

- data/856/870/85/85687085.geojson 
- data/856/871/35/85687135.geojson

**Comment by stepps00** [comment]
@nvkelso - all "to do" items are taken care of. I'll QA once more, then likely merge.

**Comment by nvkelso** [comment]
🎉

**Pull request merged**
